site_name: Kusama User Guide
site_description: The Kusama knowledge base
site_author: 'Web3 Foundation'
site_url: https://guide.kusama.network

nav:
 - Home: index.md
 - Claims: claims.md
 - Community: community.md

# Configuration for the Material theme
theme:
  name: null
  custom_dir: 'mkdocs-material/material'
  language: 'en'
  palette:
    primary: 'grey'
    accent: 'pink'
  font:
    text: 'PT Sans'
    code: 'Ubuntu Mono'
  favicon: 'img/favicon.ico'
  logo: 'img/Polkadot_symbol_color.png'
  feature:
    tabs: false

# Extra css for further customization
extra_css:
  - 'stylesheets/extra.css'

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - https://research.web3.foundation/en/latest/mathjax-config.js

# Repository that houses the source code for this site. This
# is needed to render the nice GH link on the top right.
repo_name: 'kusamanetwork/userguide'
repo_url: 'https://github.com/kusamanetwork/userguide'

# Social links
extra:
  social:
    - type: 'github'
      size: 'lg'
      link: 'https://github.com/paritytech/polkadot'
    - type: 'twitter'
      size: 'lg'
      link: 'https://twitter.com/kusamanetwork'
    - type: 'medium'
      size: 'lg'
      link: 'https://medium.com/@polkadotnetwork'

footer:
  logo: 'img/Polkadot_Logotype_white.png'

markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: false
    - toc:
        permalink: true
    - mdtooltips
