version: 2

jobs:
  tests:
    docker:
      - image: python:3.6-alpine3.9
    steps:
      - checkout
      - run:
          command: |
            pip install virtualenv

            python3.6 -mvirtualenv --no-site-packages --no-download .

            source bin/activate

            pip install -r requirements.txt

            mkdocs build --clean --site-dir _build/html --config-file ./mkdocs.yml
      - run:
          name: serve
          background: true
          command: |
            source bin/activate

            mkdocs serve

      - run:
          name: check links
          command: |
            pip install pylinkvalidator html5lib

            sed -i -e 's/\(decode("ascii")\)/\1.replace(" ", "%20")/g' /usr/local/lib/python3.6/site-packages/pylinkvalidator/urlutil.py

            pylinkvalidate.py --parser=html5lib -P http://localhost:8000


  spellCheck:
    docker:
      - image: node:10.15-alpine
    steps:
      - checkout
      - run:
          command: |
            npm i

            npm run spellcheck

workflows:
  version: 2
  build_and_tests:
    jobs:
      - tests:
          filters:
            tags:
              only: /.*/
      - spellCheck:
          filters:
            tags:
              only: /.*/
